//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mime.net.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mime.net.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # This file maps Internet media types to unique file extension(s).
        ///# Although created for httpd, this file is used by many software systems
        ///# and has been placed in the public domain for unlimited redisribution.
        ///#
        ///# The table below contains both registered and (common) unregistered types.
        ///# A type that has no unique extension can be ignored -- they are listed
        ///# here to guide configurations toward known types and to make it easier to
        ///# identify &quot;new&quot; types.  File extensions are also commonly used to indicate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mimeTypes {
            get {
                return ResourceManager.GetString("mimeTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # What: WebVTT
        ///# Why: To allow formats intended for marking up external text track resources.
        ///# http://dev.w3.org/html5/webvtt/
        ///# Added by: niftylettuce
        ///text/vtt  vtt
        ///
        ///# What: Google Chrome Extension
        ///# Why: To allow apps to (work) be served with the right content type header.
        ///# http://codereview.chromium.org/2830017
        ///# Added by: niftylettuce
        ///application/x-chrome-extension  crx
        ///
        ///# What: HTC support
        ///# Why: To properly render .htc files such as CSS3PIE
        ///# Added by: niftylettuce
        ///text/x-component  htc
        ///
        ///# What: HTM [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nodeTypes {
            get {
                return ResourceManager.GetString("nodeTypes", resourceCulture);
            }
        }
    }
}
